# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d79024bf5c0e0bd5d85435c05a0c441b639b26cfd2dbed19ea9754c130324bdda8ee85a7b77785ebf8802f70ba9b1465e265c7e39acace4266326664748268fa

test:
  secret_key_base: 1d1762e8ad77e19abf58ad42f934e16ac64acf6573ee06df355aa32e8e288cc1fe654e28196ae949ff249682dd4eee5efc19b6b4cbbefcf1d3c7775e816a78d4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
